ExternalProject_Add(qlitehtml
GIT_REPOSITORY "git://code.qt.io/playground/qlitehtml.git"
GIT_TAG        "7e8eb0f5eaee53b0aeb04208bdaba74fcffc3a3f"  # b2137
GIT_SHALLOW    ON
BUILD_COMMAND cmake --build . --parallel
INSTALL_COMMAND cmake --install .
CMAKE_ARGS     -DCMAKE_INSTALL_PREFIX=${SB_INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DQLITEHTML_LIBRARY_TYPE=STATIC -DQLITEHTML_EXPORT=kaho -DQLITEHTML_DEVEL_COMPONENT=devel -DQLITEHTML_USE_SYSTEM_LITEHTML=OFF
)