ExternalProject_Add(cmark_gfm
    GIT_REPOSITORY "https://github.com/github/cmark-gfm"
    GIT_TAG        "587a12bb54d95ac37241377e6ddc93ea0e45439b"  # 0.29.0.gfm.13
    GIT_SHALLOW    ON
    GIT_SUBMODULES ""
    CMAKE_ARGS -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER} -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER} -DCMAKE_INSTALL_PREFIX=${SB_INSTALL_PREFIX} -DCMARK_SHARED=OFF -DCMARK_STATIC=ON -DCMARK_TESTS=OFF
)
