# - plugins:
#     - avaly/gcp-secret-manager#v1.1.1:
#         credentials_file: /etc/gcloud-credentials.json
#         env:
#           SECRET_VAR: my-secret-name
#           OTHER_SECRET_VAR: my-other-secret-name

steps:
#  - label: "🐧 Linux build"
#    agents:
#      os: linux
#    env:
#      KAHO_OS: "linux"
#      KAHO_OS_VARIANT: "{{matrix.variant}}"
#      KAHO_ARCH: "{{matrix.arch}}"
#    command: ./bin/ci_build.sh
#    matrix:
#      setup:
#        arch:
#          - "amd64"
#        variant:
#          - "ubuntu"
  - label: "🍎 Mac build"
    agents:
      os: darwin
    env:
      KAHO_OS: "{{matrix.os}}"
      KAHO_ARCH: "{{matrix.arch}}"
    commands:
      - ./bin/ci_mac_superbuild.sh
      - ./bin/ci_build.sh
    matrix:
      setup:
        arch:
          - "arm64"
        os:
          - "darwin"
