steps:
  # Linux Steps
  - label: ":penguin: Build (Linux)"
    agents:
      os: linux
    commands:
      - mkdir -p build
      - cd build
      - cmake ..
      - cmake --build . --parallel -- -j8
